# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          source: "."
          target: "/var/www/html"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          BLAHBLAHBLAH: "hey from prod"
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          envs: TWILIO_ACCOUNT_SID,TWILIO_AUTH_TOKEN,BLAHBLAHBLAH
          script: |
            cd /var/www/html
            npm install
            rm -rf ecosystem.config.js
            touch ecosystem.config.js
            echo >> ecosystem.config.js "module.exports = {
              apps: [
                {
                  name: \"backyard_server\",
                  script: \"./server.js\",
                  logs: \"./logs/app.log\",
                  watch: true,
                  env: {
                    PORT: 8080,
                    NODE_ENV: \"production\",
                    BLAHBLAHBLAH: \"$BLAHBLAHBLAH\",
                    TWILIO_ACCOUNT_SID: \"$TWILIO_ACCOUNT_SID\",
                    TWILIO_AUTH_TOKEN: \"$TWILIO_AUTH_TOKEN\",
                  },
                },
              ],
            };"
            npm start
